apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-nfs

helmcharts:
  # https://github.com/kubernetes-csi/csi-driver-nfs/tree/master
  # https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/charts
  # https://artifacthub.io/packages/helm/csi-driver-nfs/csi-driver-nfs
  - name: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    version: 4.11.0
    releaseName: csi-nfs
    # apparently helm will suppress the generation of CRDs by default 
    #includeCRDs: true
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - storageclass.yaml
