---
# we use this storageClass for dynamically allocating NFS PersistentVolumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  labels:
    app.kubernetes.io/instance: csi-nfs
    app.kubernetes.io/name: csi-driver-nfs
parameters:
  server: wunderhort-nfs.irminsul
  share: /wunderhort/nekropolis-csi-nfs
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
allowVolumeExpansion: true
